#!/bin/bash
# Auto-generated by setup_services.sh — rotate display AND touch to landscape.
# Retries: at boot the panel output is often not ready when this first runs
# (that is why rotation worked after setup but reverted on reboot).
ROT="left"
MATRIX="0 -1 1 1 0 0 0 0 1"

log() { echo "[rotate-display] $*"; }

# Rotate display + touch once. Returns 0 only when the display is confirmed
# landscape (active geometry wider than tall), so the caller knows to stop.
apply() {
    local out geo w h
    out=$(xrandr --query 2>/dev/null | awk '/ connected/{print $1; exit}')
    [ -z "$out" ] && return 1
    geo=$(xrandr --query 2>/dev/null | grep -E "^$out connected" \
          | grep -oE '[0-9]+x[0-9]+\+[0-9]+\+[0-9]+' | head -n1)
    [ -z "$geo" ] && return 1            # output present but no active mode yet

    xrandr --output "$out" --rotate "$ROT" 2>/dev/null || true

    # Touch: apply the matching transform to every touchscreen, by device
    # (identified by exposing a Calibration Matrix — mice/keyboards do not),
    # so we never depend on the Xorg InputClass matching this panel.
    for id in $(xinput list --id-only 2>/dev/null); do
        if xinput list-props "$id" 2>/dev/null | grep -qi "Calibration Matrix"; then
            xinput set-prop "$id" "Coordinate Transformation Matrix" $MATRIX 2>/dev/null || true
        fi
    done

    geo=$(xrandr --query 2>/dev/null | grep -E "^$out connected" \
          | grep -oE '[0-9]+x[0-9]+\+[0-9]+\+[0-9]+' | head -n1)
    w=${geo%%x*}; h=${geo#*x}; h=${h%%+*}
    [ -n "$w" ] && [ -n "$h" ] && [ "$w" -gt "$h" ]
}

for i in $(seq 1 20); do
    if apply; then log "landscape applied and verified (try $i)"; exit 0; fi
    log "display output not ready yet (try $i)…"
    sleep 1
done
log "gave up after 20 tries — check 'xrandr --query'"
exit 0
